Repository 2023SVBootcamp-Team-H/frontend, pull requests merged in 2023-07, with the labels that each got.

#2 Fe/#1 메인페이지 퍼블리싱
  package-lock.json
  package.json
  src/App.tsx
  src/assets/fonts/HahmletBold.ttf
  src/assets/fonts/HahmletLight.ttf
  src/assets/fonts/HahmletMedium.ttf
  src/assets/fonts/HahmletRegular.ttf
  src/assets/fonts/HahmletSemiBold.ttf
  src/assets/images/back.png
  src/assets/images/back2.png
  src/assets/images/backgroudLight.png
  src/assets/images/backgroudSparkle.png
  src/assets/images/backgroundImage.png
  src/assets/images/wizard.png
  src/assets/images/wizardCenter.png
  src/assets/react.svg
  src/components/.gitkeep
  src/components/statistics.tsx
  src/pages/.gitkeep
  src/pages/MainPage.tsx
  src/reset.css
  tailwind.config.js
Labels: 퍼블리싱

#4 Fe/#3 책 컴포넌트 퍼블리싱
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/back.png
  src/assets/images/back2.png
  src/assets/images/backgroudLight.png
  src/assets/images/backgroudSparkle.png
  src/assets/images/backgroundImage.png
  src/assets/images/backgroundMain.png
  src/assets/images/backgroundSub.png
  src/assets/images/category/baby.png
  src/assets/images/category/course.png
  src/assets/images/category/family.png
  src/assets/images/category/friendship.png
  src/assets/images/category/future.png
  src/assets/images/category/health.png
  src/assets/images/category/hobby.png
  src/assets/images/category/job.png
  src/assets/images/category/love.png
  src/assets/images/category/military.png
  src/assets/images/category/money.png
  src/assets/images/category/sports.png
  src/assets/images/category/study.png
  src/assets/images/category/wedding.png
  src/assets/images/frame.png
  src/assets/images/wizard.png
  src/assets/images/wizardCenter.png
  src/components/Book.tsx
  src/components/statistics.tsx
  src/pages/BookPage.tsx
  src/pages/MainPage.tsx
  tailwind.config.js
Labels: 퍼블리싱

#8 Fe/#5 고민 카테고리 페이지 퍼블리싱
  src/assets/images/category/care.png
  src/components/SelectWorryL.tsx
  src/components/SelectWorryR.tsx
  src/pages/BookPage.tsx
  tailwind.config.js
Labels: 퍼블리싱

#10 Fe/#7 만족도 조사 모달창 퍼블리싱
  src/App.tsx
  src/assets/images/closeIcon.svg
  src/assets/images/popularbuttonIcon.svg
  src/assets/images/star.svg
  src/assets/images/starYellow.svg
  src/components/SatisfactionModal.tsx
  src/pages/MainPage.tsx
Labels: 퍼블리싱

#11 feat: 인격 선택 페이지 퍼블리싱
  src/App.tsx
  src/assets/images/category/friend.png
  src/assets/images/category/grandma.png
  src/assets/images/category/parents.png
  src/assets/images/category/teacher.png
  src/assets/images/category/youngboy.png
  src/components/SelectCharL.tsx
  src/components/SelectCharR.tsx
  src/pages/BookPageTwo.tsx
Labels: 퍼블리싱

#14 Fe/#12 통계 페이지 퍼블리싱
  package-lock.json
  package.json
  src/App.tsx
  src/assets/images/popularbuttonwhiteIcon.svg
  src/components/StatisticsL.tsx
  src/components/StatisticsR.tsx
  src/components/statistics.tsx
  src/pages/BookPageFour.tsx
  src/pages/MainPage.tsx
Labels: 퍼블리싱

#19 Fe/#18 flip 라이브러리 적용
  package-lock.json
  package.json
  src/App.tsx
  src/components/Book.tsx
  src/components/PageFlipAnimation.tsx
  src/components/TestBook.tsx
  src/components/test.tsx
  src/pages/BookPage.tsx
  src/pages/BookPageFour.tsx
  src/pages/BookPageThree.tsx
  src/pages/BookPageTwo.tsx
Labels: 디자인

#20 Fe/#16 버튼 관련 기능 구현
  .eslintrc.json
  src/components/InputWorryL.tsx
  src/components/InputWorryR.tsx
  src/components/SatisfactionModal.tsx
  src/components/SelectCharR.tsx
  src/components/SelectWorryL.tsx
  src/components/SelectWorryR.tsx
  src/pages/BookPage.tsx
  src/pages/BookPageThree.tsx
  src/pages/BookPageTwo.tsx
Labels: 기능구현

#22 Fe/#21 Book 관련 코드 보완
  src/App.tsx
  src/components/InputWorryL.tsx
  src/components/InputWorryR.tsx
  src/components/PageFlipAnimation.tsx
  src/components/SatisfactionModal.tsx
  src/components/TestBook.tsx
  src/pages/BookPage.tsx
  src/pages/BookPageThree.tsx
  src/pages/BookPageTwo.tsx
  src/pages/MainPage.tsx
  src/pages/SatisfactionPage.tsx
Labels: 리팩토링

#25 feat: Lottie 이용한 로딩화면 파일 추가
  package-lock.json
  package.json
  src/assets/lottie.tsx
  src/assets/lottie/loadingLottie.json
  src/components/InputWorryR.tsx
  src/components/LoadingScreen.tsx
Labels: 기능구현

#26 Fe/#21 고민 보내기 Recoil
  .eslintrc.json
  index.html
  package-lock.json
  package.json
  src/App.tsx
  src/Recoil.tsx
  src/assets/images/witchmindIcon.png
  src/components/FlipBook.tsx
  src/components/InputWorryL.tsx
  src/components/PageFlipAnimation.tsx
  src/components/SelectCharR.tsx
  src/components/SelectWorryL.tsx
  src/components/SelectWorryR.tsx
  src/components/TestBook.tsx
  src/pages/BookPage.tsx
  src/pages/BookPageThree.tsx
  src/pages/BookPageTwo.tsx
  src/pages/MainPage.tsx
  src/pages/SatisfactionPage.tsx
Labels: 기능구현, 리팩토링

#28 Fe/#27 Recoil 마무리
  src/Character.tsx
  src/Recoil.tsx
  src/assets/images/waitLoading.png
  src/assets/lottie/loadingLottie.json
  src/components/FlipBook.tsx
  src/components/InputWorryL.tsx
  src/components/InputWorryR.tsx
  src/components/LoadingScreen.tsx
  src/components/SatisfactionModal.tsx
Labels: 기능구현

#30 Fe/#29 인격 선택 페이지 기능 구현
  src/Character.tsx
  src/assets/images/character/friendF_off.png
  src/assets/images/character/friendF_on.png
  src/assets/images/character/friendT_off.png
  src/assets/images/character/friendT_on.png
  src/assets/images/character/gradeTwo_off.png
  src/assets/images/character/gradeTwo_on.png
  src/assets/images/character/grandma_off.png
  src/assets/images/character/grandma_on.png
  src/assets/images/character/rapper_off.png
  src/assets/images/character/rapper_on.png
  src/components/SelectCharR.tsx
Labels: 기능구현

#31 Fe/#27 Recoil, API 연동
  .eslintrc.json
  package.json
  src/Recoil.tsx
  src/components/BarChart.tsx
  src/components/InputWorryL.tsx
  src/components/InputWorryR.tsx
  src/components/SatisfactionModal.tsx
  src/components/SelectWorryL.tsx
  src/components/SelectWorryR.tsx
  src/components/StatisticsL.tsx
  src/components/StatisticsR.tsx
  src/pages/MainPage.tsx
  src/pages/SatisfactionPage.tsx
Labels: 기능구현

#34 Fe/#32 인격 이미지 관련 기능구현
  src/Character.tsx
  src/components/BarChart.tsx
  src/components/InputWorryL.tsx
  src/components/InputWorryR.tsx
  src/components/SatisfactionModal.tsx
  src/components/SelectCharR.tsx
  src/components/StatisticsL.tsx
  src/pages/SatisfactionPage.tsx
Labels: 기능구현

#41 Fe/#40 닉네임 페이지 추가
  justinaguilar.css
  package-lock.json
  package.json
  src/assets/images/nicknameL.png
  src/assets/images/witch.png
  src/components/FlipBook.tsx
  src/components/NickameL.tsx
  src/components/NickameR.tsx
  src/pages/BookPage.tsx
  src/pages/BookPageTwo.tsx
  src/pages/NicknamePage.tsx
Labels: 기능구현

#43 Fe/#39 bgm 추가
  src/App.tsx
  src/Recoil.tsx
  src/assets/images/play.svg
  src/assets/images/stop.svg
  src/components/AudioButton.tsx
  src/components/AudioPlayer.tsx
  src/components/FlipBook.tsx
  src/components/NickameR.tsx
  src/pages/BookPage.tsx
  src/pages/MainPage.tsx
Labels: 기능구현

#47 FE/#46 고민 카테고리 이미지 색상 추가
  src/assets/images/category/baby.png
  src/assets/images/category/care.png
  src/assets/images/category/course.png
  src/assets/images/category/family.png
  src/assets/images/category/friendship.png
  src/assets/images/category/future.png
  src/assets/images/category/health.png
  src/assets/images/category/hobby.png
  src/assets/images/category/job.png
  src/assets/images/category/love.png
  src/assets/images/category/military.png
  src/assets/images/category/money.png
  src/assets/images/category/sports.png
  src/assets/images/category/study.png
  src/assets/images/category/wedding.png
  src/components/SelectWorryL.tsx
  src/components/SelectWorryR.tsx
Labels: 디자인

#50 [feat] : 통계창 반응형 구현
  src/assets/images/frameV.png
  src/components/StatisticsL.tsx
  src/components/StatisticsR.tsx
  src/componentsV/.gitkeep
  src/pages/SatisfactionPage.tsx
Labels: 기능구현

#52 Fe/#45 반응형 웹
  src/components/FlipBook.tsx
  src/components/InputWorryL.tsx
  src/components/InputWorryR.tsx
  src/components/LoadingScreen.tsx
  src/components/SatisfactionModal.tsx
  src/components/SelectCharL.tsx
  src/components/SelectCharR.tsx
  src/components/SelectWorryL.tsx
  src/components/SelectWorryR.tsx
  src/components/StatisticsL.tsx
  src/components/StatisticsR.tsx
  src/pages/BookPage.tsx
  src/pages/BookPageThree.tsx
  src/pages/BookPageTwo.tsx
  src/pages/SatisfactionPage.tsx
Labels: 기능구현, 디자인
